services:
  mysql-tunnel:
    image: alpine:latest
    container_name: rds-tunnel
    user: root
    environment:
      - SSH_KEY=/root/.ssh/key.pem
    volumes:
      - ./ssh:/root/.ssh
    command: |
      /bin/sh -c '
        apk add --no-cache openssh-client netcat-openbsd &&
        chmod 600 /root/.ssh/key.pem &&
        ssh -o "StrictHostKeyChecking=no" \
            -o "ServerAliveInterval=60" \
            -o "ServerAliveCountMax=3" \
            -N -L "0.0.0.0:3306:${RDS_ENDPOINT}:3306" \
            ubuntu@${EC2_IP} \
            -i /root/.ssh/key.pem
      '
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - tunnel-network

networks:
  tunnel-network:
    driver: bridge